---
- name: Check hostname on RHEL systems
  hosts: all
  tasks:
    - name: Hello
      shell: /usr/bin/uptime | grep -ohe 'up .*' | sed 's/,//g' | awk '{ print $2" "$3 }'
      changed_when: False
      register: uptime
