name: Docker Build & Push

on:
  push:
    branches:
      - main  # Adjust this to the branch you want to trigger the workflow on
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ sameer8i8 }}
          password: ${{ FINAL_YEAR }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .  # Adjust the path if your Dockerfile is in a subdirectory
          push: true
          tags: sameer8i8/final-year:v1 # Change this to your Docker Hub repo and image name
